%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/nadineigonin/Dropbox/MAC/Documents/Research/ActiveSeismic/ROC2025_Testing/SourceTesting/TB_INT00136.csv
%
% Auto-generated by MATLAB on 06-May-2025 18:56:48

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [1, 5];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["week2365", "ms240471938", "Subms60926"];
opts.VariableTypes = ["string", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "week2365", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "week2365", "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["ms240471938", "Subms60926"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["ms240471938", "Subms60926"], "ThousandsSeparator", ",");

% Import the data
TBINT00136 = readtable("/Users/nadineigonin/Dropbox/MAC/Documents/Research/ActiveSeismic/ROC2025_Testing/SourceTesting/TB_INT00136.csv", opts);


%% Clear temporary variables
clear opts